//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userdetail
    {
        public int userid { get; set; }
        public string username { get; set; }
        public string emailid { get; set; }
        public string gender { get; set; }
        public string address { get; set; }
        public string mobileno { get; set; }
        public string pincode { get; set; }
    }
}
